//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by OrderServ.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_ORDERSTYPE                  129
#define IDR_LOG                         130
#define IDD_SECIFO                      130
#define IDR_SECIFO                      131
#define IDD_EQUITY                      132
#define IDR_EQUITY                      132
#define IDD_TRADERS                     133
#define IDR_TRADERS                     133
#define IDR_LOGINLOG                    134
#define IDR_OrderRoute                  135
#define IDD_DIGIPINPUT                  136
#define IDR_SCRIPT                      136
#define IDD_DLGBALANCE                  137
#define IDD_ROUTELST                    140
#define IDD_ROUTECFG                    141
#define IDD_DLGMSG                      142
#define IDR_MenuPopUp                   144
#define IDD_DIALOG1                     147
#define IDC_STGRID                      1000
#define IDC_BLoadShortLst               1001
#define IDC_EDSECSYM                    1002
#define IDC_CHKSHORT                    1003
#define IDC_CHKMARG                     1004
#define IDC_COMBMKT                     1005
#define IDC_CHKHIRISK                   1006
#define IDC_EDSHORTSIZE                 1007
#define IDC_BLoadUnShortLst             1008
#define IDC_EDSOESTIRE                  1009
#define IDC_BChange                     1010
#define IDC_BDEL                        1011
#define IDC_BClear                      1012
#define IDC_BComitChange                1013
#define IDC_BUndel                      1014
#define IDC_BFind                       1015
#define IDC_BSort                       1016
#define IDC_PROGCOMIT                   1017
#define IDC_DBP                         1018
#define IDC_BRemoveAll                  1018
#define IDC_NBP                         1019
#define IDC_EQ                          1020
#define IDC_MEQ                         1021
#define IDC_ACC                         1022
#define IDC_BLoadBuypower               1023
#define IDC_BLoadEquity                 1024
#define IDC_BRefresh                    1027
#define IDC_BKickOut                    1028
#define IDC_EDIP                        1029
#define IDC_BBlock                      1029
#define IDC_EDPORT                      1030
#define IDC_BQuote                      1031
#define IDC_BSortAsc                    1032
#define IDC_BSortDec                    1033
#define IDC_BCount                      1034
#define IDC_EDLOGOUTMSG                 1035
#define IDC_BConnect                    1036
#define IDC_BDISCON                     1037
#define IDC_BConfig                     1038
#define IDC_EDUID                       1039
#define IDC_EDPWD                       1040
#define IDC_BDisConAll                  1041
#define IDC_STVER                       1043
#define IDC_STIFO                       1046
#define IDC_BLoadCCSBalance             1047
#define IDC_EDMSG                       1048
#define IDC_STICON                      1049
#define IDC_STRoute                     1050
#define IDC_EDSTART                     1052
#define IDC_EDSTOP                      1053
#define IDC_CAutoConnect                1054
#define IDC_EDPORT1                     1057
#define IDC_EDPORT2                     1059
#define IDC_EDIP1                       1061
#define IDC_EDIP2                       1062
#define IDC_BCrash                      1062
#define IDC_BPref                       1063
#define IDC_CHKCancelReplace            1064
#define IDC_EDEXCHFILTER                1065
#define IDC_CHKHide                     1066
#define IDC_CHKDisableCustomerOrder     1067
#define DB_TMP                          32771
#define ID_VIEW_CFG                     32772
#define ID_VIEW_LOG                     32773
#define ID_AAA_TMP1                     32774
#define ID_AAA_POSITION                 32775
#define ID_AAA_ONLINETRADER             32779
#define ID_AAA_ORDERS                   32780
#define ID_ORDERROUTE_ISLD              32781
#define ID_AAA_TRADES                   32783
#define ID_DATA_LOADINITEQUITY          32784
#define ID_DATA_LOADEQUITY              32785
#define ID_DATA_SAVEEQUITY              32786
#define ID_AAA_ACCOUNT                  32787
#define ID_AAA_DEAL                     32788
#define ID_AAA_TICKET                   32789
#define ID_DATA_LSHTLST                 32790
#define ID_ORDERROUTE_SOESSNET          32791
#define ID_ORDERROUTE_DOT               32793
#define ID_DATA_SAVEDATA                32800
#define ID_ORDERROUTE_ARCA              32801
#define ID_ORDERROUTE_BRUT              32803
#define ID_ORDERROUTE_REDI              32807
#define ID_ORDERROUTE_INCA              32809
#define ID_ORDERROUTE_NITE              32811
#define ID_TOOLS_SECIFO                 32815
#define ID_TOOLS_EQUITY                 32816
#define ID_VIEW_TRADERS                 32819
#define ID_ORDERROUTE_TEST              32820
#define ID_TOOLS_BALANCE                32837
#define ID_VIEW_LOGINLOG                32838
#define ID_DATA_EXPORTPOSITION          32839
#define ID_BUTTON32843                  32843
#define ID_TOOLS_LOADLOGINCTRL          32844
#define ID_DATA_COUNTING                32845
#define ID_ORDERROUTE_GNET              32848
#define ID_ORDERROUTE_CONFIG            32855
#define ID_VIEW_THREADS                 32856
#define ID_DATA_RECOVER_SAVETRADES      32858
#define ID_AAA_TEST                     32859
#define ID_TOOLS_LOADMMUNTRADEABLE      32860
#define ID_DATA_SOD_QUEST               32862
#define ID_DATA_SOD_SHORTLIST           32863
#define ID_DATA_SOD_UNSHORTLIST         32864
#define ID_ROUTE_CONNECT                32865
#define ID_ROUTE_DISCONNECT             32866
#define ID_ROUTE_CONFIG                 32867
#define ID_ROUTE_CONNECTALL             32868
#define ID_ROUTE_DISCONNECTALL          32869
#define ID_DATA_SOD_BPEQUITY            32873
#define ID_TOOLS_LOADROUTECTRL          32874
#define ID_TOOLS_COMMAND                32875
#define ID_TOOLS_SCRIPTLIST             32876
#define ID_LogFile                      32877
#define ID_TOOLS_DBRECONN               32878
#define ID_TOOLS_RECALCUATEECNFEE       32879

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        148
#define _APS_NEXT_COMMAND_VALUE         32880
#define _APS_NEXT_CONTROL_VALUE         1068
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
